import argparse
import numpy as np
import cv2
import matplotlib.pyplot as plt

def main():
    parser = argparse.ArgumentParser(description="Visualize raw float32 Depth Anything Nano output from ESP32 SD card.")
    parser.add_argument("--bin", type=str, help="Path to input .bin file", default="output.bin")
    parser.add_argument("--out", type=str, help="Path to output .png image", default="depth_map.png")
    
    args = parser.parse_args()
    
    # Read the 16x16 float32 map generated by ESP32
    print(f"Reading {args.bin}...")
    try:
        with open(args.bin, 'rb') as f:
            raw_data = f.read()
    except FileNotFoundError:
        print(f"Error: {args.bin} not found. Did you copy it from the SD card?")
        return

    # Check size (16x16 floats = 256 * 4 bytes = 1024 bytes)
    expected_bytes = 16 * 16 * 4
    if len(raw_data) != expected_bytes:
        print(f"Warning: Expected {expected_bytes} bytes, got {len(raw_data)} bytes.")
    
    # Flatten and reshape to 16x16
    float_array = np.frombuffer(raw_data, dtype=np.float32)
    depth_map = float_array.reshape((16, 16))
    
    print(f"Min depth: {depth_map.min():.4f}, Max depth: {depth_map.max():.4f}")
    
    # Normalize to 0-255 for visualization
    depth_norm = cv2.normalize(depth_map, None, 0, 255, cv2.NORM_MINMAX, dtype=cv2.CV_8U)
    
    # Optionally apply colormap
    depth_color = cv2.applyColorMap(depth_norm, cv2.COLORMAP_INFERNO)
    
    # Resize up to 224x224 linearly for standard display
    depth_display = cv2.resize(depth_color, (224, 224), interpolation=cv2.INTER_CUBIC)
    
    cv2.imwrite(args.out, depth_display)
    print(f"Depth map successfully saved to {args.out}")
    
    # Display if running interactively
    plt.imshow(cv2.cvtColor(depth_display, cv2.COLOR_BGR2RGB))
    plt.title("ESP32S3 Hardware Inference Output")
    plt.axis('off')
    plt.show()

if __name__ == "__main__":
    main()
